-- AlterEnum
ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_PROCESSING';
ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'PAUSED';

-- AlterTable
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "requirementItems" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "minimumPostDate" TIMESTAMP(3);
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "campaignLink" TEXT;
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "telegramGroupLink" TEXT;
